### ISSUE TITLE
Add esm "module" entrypoint for package

### ISSUE THREAD

**Issue by shinobi5** [andybelldesign/beedle#23]
Any chance an esm `module` entry point can be added to `package.json`?

If I want to use a tool like [@pikapkg/web](https://github.com/pikapkg/web) without using a bundler it's not currently supported because it doesn't have an esm format output file that can be used with the `module` property of the package.

See this search result:
https://www.pika.dev/search?q=beedle

Possible to generate an esm format file and add this to the package as an option?

I can create a PR if this sounds OK.

**Comment by andybelldesign** [comment]
Hey @shinobi5! If you want to do a PR, that would be great because that isn't really my expertise at all. 

Thank you :)

**Comment by shinobi5** [comment]
Great. I'll get that sorted. Thanks.

**Comment by andybelldesign** [comment]
Fixed with #24
